// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQy6qFz-wjBKTEt9F0FLIbOw3L5mlJVQ0',
    appId: '1:896771021952:web:5215f5505a029bea5f1a65',
    messagingSenderId: '896771021952',
    projectId: 'alu-hub-3989e',
    authDomain: 'alu-hub-3989e.firebaseapp.com',
    storageBucket: 'alu-hub-3989e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH9zweU9c1-TVpKzw13e8nI1xomVJBjN8',
    appId: '1:896771021952:android:38ed18361638dc9b5f1a65',
    messagingSenderId: '896771021952',
    projectId: 'alu-hub-3989e',
    storageBucket: 'alu-hub-3989e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD3s5FfqR3PdBZn8-XzD5NTSJy5tmcTz4',
    appId: '1:896771021952:ios:f6fbbc90686e4f6e5f1a65',
    messagingSenderId: '896771021952',
    projectId: 'alu-hub-3989e',
    storageBucket: 'alu-hub-3989e.firebasestorage.app',
    iosBundleId: 'com.example.aluHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD3s5FfqR3PdBZn8-XzD5NTSJy5tmcTz4',
    appId: '1:896771021952:ios:f6fbbc90686e4f6e5f1a65',
    messagingSenderId: '896771021952',
    projectId: 'alu-hub-3989e',
    storageBucket: 'alu-hub-3989e.firebasestorage.app',
    iosBundleId: 'com.example.aluHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQy6qFz-wjBKTEt9F0FLIbOw3L5mlJVQ0',
    appId: '1:896771021952:web:cc425bf949dc99315f1a65',
    messagingSenderId: '896771021952',
    projectId: 'alu-hub-3989e',
    authDomain: 'alu-hub-3989e.firebaseapp.com',
    storageBucket: 'alu-hub-3989e.firebasestorage.app',
  );
}
